name: Run Python Script in Parallel

on: 
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        iteration: [1, 2, 3, 4, 5]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add additional installation commands if needed
        # pip install -r requirements.txt

    - name: Run script in parallel
      run: python your_script.py &
